CREATE TABLE IF NOT EXISTS JUGADORES (
    ID_JUGADOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    GRUPO INT,
    PUNTAJE INT
);
CREATE TABLE IF NOT EXISTS PISTAS (
    NOMBRE VARCHAR(100) NOT NULL PRIMARY KEY,
    INFORMACION VARCHAR(5000),
    IMAGEN VARCHAR(1000)
);
CREATE TABLE IF NOT EXISTS TRIVIA (
    ID_PREGUNTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    PREGUNTA VARCHAR(200),
    RESPUESTA_CORRECTA VARCHAR(1000),
    RESPUESTA_INCORRECTA1 VARCHAR(256),
    RESPUESTA_INCORRECTA2 VARCHAR(256),
    RESPUESTA_INCORRECTA3 VARCHAR(256)
);

ALTER TABLE PISTAS ADD CONSTRAINT PISTAS_NOMBRE_fk FOREIGN KEY (NOMBRE) REFERENCES TRIVIA (NOMBRE);

ALTER TABLE JUGADORES ADD COLUMN ULTIMA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE JUGADORES ADD COLUMN ultima_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
