# .github/workflows/azure-deploy.yml
name: Deploy to Azure

on:
  push:
    branches:
      - main  # Cambia por la rama que uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: explorasistemas
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

